apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus3
    spec:
      containers:
      - name: nexus3
        image: sonatype/nexus3:latest
        ports:
        - containerPort: 8081