kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-claim
  labels:
    group: artifactory-k8s-demo
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
