kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-pv
  labels:
    group: artifactory-k8s-demo
    type: amazonEBS
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-0e87424db654434e3
    fsType: ext4