apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgresql-k8s-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-k8s
        group: artifactory-k8s-demo
      annotations:
        pod.beta.kubernetes.io/init-containers: '[{
          "name": "remove-lost-found",
          "image": "busybox:1.26.2",
          "command": ["rm", "-rf", "/var/lib/postgresql/data/lost+found"],
          "volumeMounts": [{
              "name": "postgresql-volume",
              "mountPath": "/var/lib/postgresql/data"
            }],
          "imagePullPolicy": "IfNotPresent"
        }]'
    spec:
      containers:
      - name: postgresql-k8s
        image: docker.bintray.io/postgres:9.5.2
        env:
        - name: POSTGRES_DB
          value: artifactory
        - name: POSTGRES_USER
          value: artifactory
        - name: POSTGRES_PASSWORD
          value: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgresql-volume
      volumes:
      - name: postgresql-volume
        persistentVolumeClaim:
          claimName: postgresql-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-k8s-service
  labels:
    app: postgresql-k8s-service
    group: artifactory-k8s-demo
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: postgresql-k8s
